### ISSUE TITLE
No SPM sessions in ToC

### ISSUE THREAD

**Issue by mcichecki** [Blackjacx/WWDC#26]
is there any reason why you didn't add SPM sessions from this year? There are 2 sessions which are not in ToC:
- [Adopting Swift Packages in Xcode (408)](https://developer.apple.com/videos/play/wwdc2019/408/)
- [Creating Swift Packages (410)](https://developer.apple.com/videos/play/wwdc2019/410/)

**Comment by Blackjacx** [comment]
Hey, just because the whose site is still work in progress. They definitely have a high priority since I work on a library which I want to distribute via SPM. So expect them soon 👍

**Comment by Blackjacx** [comment]
OK issue resolved and session notes added: 

https://github.com/Blackjacx/WWDC#adopting-swift-packages-in-xcode

https://github.com/Blackjacx/WWDC#creating-swift-packages
