### ISSUE TITLE
Previous WWDCs?

### ISSUE THREAD

**Issue by martinstoyanov** [Blackjacx/WWDC#36]
First off this is awesome! Just wanted to know, is there something similar for previous WWDCs?

**Comment by Blackjacx** [comment]
Nope not that I know ^^

**Comment by martinstoyanov** [comment]
Thanks! Would be a great effort to do more WWDCs, I might do one or two PRs when I get the time. :)

**Comment by Blackjacx** [comment]
Thanks a lot that would be great 🤙
