### ISSUE TITLE
Fix progress.sh to display the progress of the session notes that are done

### ISSUE THREAD

**Issue by rogerluan** [Blackjacx/WWDC#56]

**Comment by Blackjacx** [comment]
This works already :-) Try it out 👍

**Comment by rogerluan** [comment]
I was thinking more something like this:

![Progress](https://progress-bar.dev/13/?scale=185&title=Progress&width=600&suffix=%20/%20185%20Sessions)

I'll submit a PR :)

**Comment by Blackjacx** [comment]
I merged it 🙏
