### ISSUE TITLE
Upgrade it for WWDC 2021 ?

### ISSUE THREAD

**Issue by Matttx** [Blackjacx/WWDC#79]
Hey ! I would like to know if you are going to upgrade it for the WWDC 2021 or if there is another repo that is doing the same as yours ? 

If you're going to upgrade it, I would like to contribute, thanks !

**Comment by Blackjacx** [comment]
Hey there 👋 

thanks for your request but as this is too much work and there is a great alternative I paused updated to this repo. Check out this:

https://www.wwdcnotes.com/
